=== yshamyna/issuetracker_yury_shamyna/src/main/webapp/issuetracker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/issuetracker" 
	xmlns:tns="http://www.example.org/issuetracker">
	
	<element name="issuetracker" type="tns:issuetracker" />
	
    <complexType name="issuetracker">
 		<sequence>
  			<element name="roles" type="tns:roles" minOccurs="1" maxOccurs="1" /> 
  			<element name="issue_statuses" type="tns:statuses" minOccurs="1" maxOccurs="1" />
  			<element name="issue_resolutions" type="tns:resolutions" minOccurs="1" maxOccurs="1" />
  			<element name="issue_priorities" type="tns:priorities" minOccurs="1" maxOccurs="1" />
  			<element name="issue_types" type="tns:types" minOccurs="1" maxOccurs="1" />
  			<element name="users" type="tns:users" minOccurs="1" maxOccurs="1" />
  			<element name="managers" type="tns:managers" minOccurs="1" maxOccurs="1" />
  			<element name="projects" type="tns:projects" minOccurs="1" maxOccurs="1" />
  			<element name="issues" type="tns:issues" minOccurs="1" maxOccurs="1" />
  		</sequence>
  	</complexType>
  
  	<complexType name="roles">
  	   	<sequence>
  	   		<element name="role" type="tns:role" minOccurs="1" maxOccurs="unbounded" />
  	   	</sequence>
  	</complexType>
  
  	<complexType name="role">
      	<attribute name="id" type="integer" use="required" /> 	
  	  	<attribute name="value" type="string" use="required" />
  	</complexType>
  
  	<complexType name="statuses">
  	   	<sequence>
  	   		<element name="status" type="tns:status" minOccurs="1" maxOccurs="unbounded" />
  	   	</sequence>
  	</complexType>
  
  	<complexType name="status">
      	<attribute name="id" type="integer" use="required" /> 	
  	  	<attribute name="value" type="string" use="required" />
  	</complexType>
  
  	<complexType name="resolutions">
  	   	<sequence>
  	   		<element name="resolution" type="tns:resolution" minOccurs="1" maxOccurs="unbounded" />
  	   	</sequence>
  	</complexType>
  
  	<complexType name="resolution">
      	<attribute name="id" type="integer" use="required" /> 	
  	  	<attribute name="value" type="string" use="required" />
  	</complexType>
  
    <complexType name="priorities">
  	   	<sequence>
  	   		<element name="priority" type="tns:priority" minOccurs="1" maxOccurs="unbounded" />
  	   	</sequence>
  	</complexType>
  
  	<complexType name="priority">
      	<attribute name="id" type="integer" use="required" /> 	
  	  	<attribute name="value" type="string" use="required" />
  	</complexType>
  
  	<complexType name="types">
  	   	<sequence>
  	   		<element name="type" type="tns:type" minOccurs="1" maxOccurs="unbounded" />
  	   	</sequence>
  	</complexType>
  
  	<complexType name="type">
     	<attribute name="id" type="integer" use="required" /> 	
  	  	<attribute name="value" type="string" use="required" />
  	</complexType>
  
  	<complexType name="users">
  		<sequence>
  			<element name="user" type="tns:user" minOccurs="0" maxOccurs="unbounded"/>
  		</sequence>
  	</complexType>
  
  	<complexType name="user">
  		<sequence>
  			<element name="first_name" type="string" />
  			<element name="last_name" type="string" />
  			<element name="email_address" type="string" />
  			<element name="role" type="integer"/>
  			<element name="password" type="string" />
  		</sequence>
  		<attribute name="id" type="integer" use="required" /> 
  	</complexType>
  	
  	<complexType name="managers">
  		<sequence>
  			<element name="manager" type="tns:manager" minOccurs="0" maxOccurs="unbounded"/>
  		</sequence>
  	</complexType>
  	
  	<complexType name="manager">
  		<sequence>
  			<element name="first_name" type="string" />
  			<element name="last_name" type="string" />
  		</sequence>
  		<attribute name="id" type="integer" use="required" /> 
  	</complexType>
  	
  	<complexType name="projects">
  		<sequence>
  			<element name="project" type="tns:project" minOccurs="0" maxOccurs="unbounded"/>
  		</sequence>
  	</complexType>
  	
  	<complexType name="project">
  		<sequence>
  			<element name="builds" type="tns:builds" />
  			<element name="name" type="string" />
  			<element name="description" type="string" />
  			<element name="build" type="integer" />
  			<element name="manager" type="integer" />
  		</sequence>
  		<attribute name="id" type="integer" use="required" /> 
  	</complexType>
  	
  	<complexType name="builds">
  		<sequence>
  			<element name="build" type="tns:build" minOccurs="0" maxOccurs="unbounded"/>
  		</sequence>
  	</complexType>
  	
  	<complexType name="build">
  		<attribute name="id" type="integer" use="required" /> 
  		<attribute name="version" type="string" use="required" />
  	</complexType>
  	
  	<complexType name="issues">
  		<sequence>
  			<element name="issue" type="tns:issue" minOccurs="0" maxOccurs="unbounded"/>
  		</sequence>
  	</complexType>
  	
  	<complexType name="issue">
  		<sequence>
  			<element name="create_date" type="tns:Data" />
  			<element name="created_by" type="integer" />
  			<element name="modify_date" type="tns:Data" />
  			<element name="modify_by" type="integer" />
  			<element name="summary" type="string" />
  			<element name="description" type="string" />
  			<element name="status" type="integer" />
  			<element name="type" type="integer" />
  			<element name="priority" type="integer" />
  			<element name="project" type="integer" />
  			<element name="build_found" type="integer" />
  			<element name="assignee" type="integer" />
  		</sequence>
  		<attribute name="id" type="integer" use="required" /> 
  	</complexType>
  	
  	<simpleType name="Data"> 
		<restriction base="string"> 
			<pattern value="[0-9]{4}-[0-9]{1,2}-[0-9]{1,2} [0-9]{1,2}:[0-9]{2} (am|pm)"/> 
		</restriction> 
	</simpleType> 
  
</schema>

=== yshamyna/issuetracker_yury_shamyna/src/main/webapp/issuetracker.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:issuetracker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			  xmlns:tns="http://www.example.org/issuetracker" 
			  xsi:schemaLocation="http://www.example.org/issuetracker issuetracker.xsd">
	<roles>
		<role id="1" value="administrator" />
		<role id="2" value="user" />
		<role id="3" value="guest" />
	</roles>
	<issue_statuses>
		<status id="1" value="new" />
		<status id="2" value="assigned" />
		<status id="3" value="in progress" />
		<status id="4" value="resolved" />
		<status id="5" value="closed" />
		<status id="6" value="reopened" />
	</issue_statuses>
	<issue_resolutions>
		<resolution id="1" value="fixed" />
		<resolution id="2" value="invalid" />
		<resolution id="3" value="wontfix" />
		<resolution id="4" value="worksforme" />
	</issue_resolutions>
	<issue_priorities>
		<priority id="1" value="critical" />
		<priority id="2" value="major" />
		<priority id="3" value="important" />
		<priority id="4" value="minor" />
	</issue_priorities>
	<issue_types>
		<type id="1" value="cosmetic" />
		<type id="2" value="bug" />
		<type id="3" value="feature" />
		<type id="4" value="perfomance" />
	</issue_types>
	<users>
		<user id="1">
			<first_name>Main</first_name>
			<last_name>Verymain</last_name>
			<email_address>Main_Verymain@mail.com</email_address>
			<role>1</role>
			<password>123</password>
		</user>
		<user id="2">
			<first_name>Sidr</first_name>
			<last_name>Sidorov</last_name>
			<email_address>Sidr_Sidorov@mail.com</email_address>
			<role>2</role>
			<password>234</password>
		</user>
		<user id="3">
			<first_name>Ivan</first_name>
			<last_name>Ivanov</last_name>
			<email_address>Ivan_Ivanov@mail.com</email_address>
			<role>2</role>
			<password>345</password>
		</user>
		<user id="4">
			<first_name>Petr</first_name>
			<last_name>Petrov</last_name>
			<email_address>Petr_Petrov@mail.com</email_address>
			<role>2</role>
			<password>456</password>
		</user>
	</users>
	<managers>
		<manager id="1">
			<first_name>John</first_name>
			<last_name>Smith</last_name>
		</manager>
		<manager id="2">
			<first_name>Tom</first_name>
			<last_name>Adams</last_name>
		</manager>
		<manager id="3">
			<first_name>Homer</first_name>
			<last_name>Simpson</last_name>
		</manager>
		<manager id="4">
			<first_name>Bob</first_name>
			<last_name>Davis</last_name>
		</manager>
		<manager id="5">
			<first_name>Ryan</first_name>
			<last_name>Cooper</last_name>
		</manager>
		<manager id="6">
			<first_name>Kyle</first_name>
			<last_name>Garcia</last_name>
		</manager>
		<manager id="7">
			<first_name>Amber</first_name>
			<last_name>Diaz</last_name>
		</manager>
	</managers>
	<projects>
		<project id="1">
			<builds>
				<build id="1" version="0.1" />
				<build id="2" version="0.2" />
				<build id="3" version="0.3" />
				<build id="4" version="0.4" />
				<build id="5" version="0.5" />
				<build id="6" version="0.6" />
				<build id="7" version="0.7" />
				<build id="8" version="0.8" />
				<build id="9" version="0.9" />
				<build id="10" version="1.0" />
			</builds>
			<name>Outlook Web App</name>
			<description>
				Outlook Web App (OWA)is a webmail service.
				Outlook Web App is used to access e-mail 
				(including support for S/MIME), calendars, 
				contacts, tasks, documents.
			</description>
			<build>10</build>
			<manager>1</manager>
		</project>
		<project id="2">
			<builds>
				<build id="1" version="0.1" />
				<build id="2" version="0.2" />
				<build id="3" version="0.3" />
				<build id="4" version="0.4" />
				<build id="5" version="0.5" />
			</builds>
			<name>Timer</name>
			<description>
				Digital counters that either increment or decrement 
				at a fixed frequency.
			</description>
			<build>4</build>
			<manager>2</manager>
		</project>
		<project id="3">
			<builds>
				<build id="1" version="0.1" />
				<build id="2" version="0.2" />
				<build id="3" version="0.3" />
				<build id="4" version="0.4" />
				<build id="5" version="0.5" />
				<build id="6" version="0.6" />
				<build id="7" version="0.7" />
				<build id="8" version="0.8" />
				<build id="9" version="0.9" />
			</builds>
			<name>Skype</name>
			<description>
				Skype is a freemium voice-over-IP service and instant 
				messaging client.
				The service allows users to communicate with peers by 
				voice using a microphone, video by using a webcam, and 
				instant messaging over the Internet.
			</description>
			<build>9</build>
			<manager>3</manager>
		</project>
		<project id="4">
			<builds>
				<build id="1" version="0.1" />
				<build id="2" version="0.2" />
				<build id="3" version="0.3" />
				<build id="4" version="0.4" />
			</builds>
			<name>GoogleTalk</name>
			<description>
				Google Talk is an instant messaging service that provides 
				both text and voice communication.
			</description>
			<build>2</build>
			<manager>4</manager>
		</project>
		<project id="5">
			<builds>
				<build id="1" version="0.1" />
				<build id="2" version="0.2" />
				<build id="3" version="0.3" />
				<build id="4" version="0.4" />
				<build id="5" version="0.5" />
				<build id="6" version="0.6" />
				<build id="7" version="0.7" />
				<build id="8" version="0.8" />
			</builds>
			<name>ICQ</name>
			<description>
				ICQ is an instant messaging computer program.
			</description>
			<build>7</build>
			<manager>5</manager>
		</project>
	</projects>
	<issues>
		<issue id="1">
			<summary>Web browsing Error has occurred</summary>
			<description>Web browsing Error has occurred</description>
			<status>3</status>
			<type>1</type>
			<priority>4</priority>
			<project>1</project>
			<build_found>10</build_found>
			<assignee>1</assignee>
		</issue>
		<issue id="2">
			<summary>Do not work increment at a fixed frequency</summary>
			<description>Do not work increment at a fixed frequency</description>
			<status>3</status>
			<type>2</type>
			<priority>3</priority>
			<project>2</project>
			<build_found>4</build_found>
			<assignee>2</assignee>
		</issue>
		<issue id="3">
			<summary>Skype will not allow to send any messages</summary>
			<description>Skype will not allow to send any messages</description>
			<status>3</status>
			<type>3</type>
			<priority>2</priority>
			<project>3</project>
			<build_found>9</build_found>
			<assignee>3</assignee>
		</issue>
		<issue id="4">
			<summary>Trouble signing in to Google Talk</summary>
			<description>Trouble signing in to Google Talk</description>
			<status>3</status>
			<type>4</type>
			<priority>1</priority>
			<project>4</project>
			<build_found>2</build_found>
			<assignee>4</assignee>
		</issue>
		<issue id="5">
			<summary>Does not close the main window</summary>
			<description>Does not close the main window</description>
			<status>3</status>
			<type>1</type>
			<priority>4</priority>
			<project>5</project>
			<build_found>7</build_found>
			<assignee>5</assignee>
		</issue>
		<issue id="6">
			<summary>Error = -2147205086</summary>
			<description>
				The browser goes through redirect loops and gives 
				the error: Error=-2147205086 in the address bar, 
				with a blank web page, user locked out and can't 
				regain access. 
			</description>
			<status>1</status>
			<type>2</type>
			<priority>3</priority>
			<project>1</project>
			<build_found>10</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="7">
			<summary>Do not work decrement at a fixed frequency</summary>
			<description>Do not work decrement at a fixed frequency</description>
			<status>1</status>
			<type>3</type>
			<priority>2</priority>
			<project>2</project>
			<build_found>4</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="8">
			<summary>Webcam not working on Skype</summary>
			<description>Webcam not working on Skype</description>
			<status>1</status>
			<type>4</type>
			<priority>1</priority>
			<project>3</project>
			<build_found>9</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="9">
			<summary>Can not change the window size</summary>
			<description>Can not change the window size</description>
			<status>1</status>
			<type>1</type>
			<priority>4</priority>
			<project>4</project>
			<build_found>2</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="10">
			<summary>Can not change the window size</summary>
			<description>Can not change the window size</description>
			<status>1</status>
			<type>2</type>
			<priority>3</priority>
			<project>5</project>
			<build_found>7</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="11">
			<summary>Error when user try login to the system</summary>
			<description>Error when user try login to the system</description>
			<status>1</status>
			<type>3</type>
			<priority>2</priority>
			<project>1</project>
			<build_found>10</build_found>
			<assignee>0</assignee>
		</issue>
		<issue id="12">
			<summary>Do not work increment and decrement at a fixed frequency</summary>
			<description>Do not work increment and decrement at a fixed frequency</description>
			<status>1</status>
			<type>4</type>
			<priority>1</priority>
			<project>2</project>
			<build_found>4</build_found>
			<assignee>0</assignee>
		</issue>
	</issues>
</tns:issuetracker>
